//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace clientewsValemas.valemas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsuariosSoap", Namespace="https://www.valefiel.com/VALEFIEL/WebServices/")]
    public partial class Usuarios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IniciarSesionAfiliadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback IniciarSesionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Usuarios() {
            this.Url = global::clientewsValemas.Properties.Settings.Default.clientewsValemas_valemas_Usuarios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IniciarSesionAfiliadoCompletedEventHandler IniciarSesionAfiliadoCompleted;
        
        /// <remarks/>
        public event IniciarSesionCompletedEventHandler IniciarSesionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.valefiel.com/VALEFIEL/WebServices/IniciarSesionAfiliado", RequestNamespace="https://www.valefiel.com/VALEFIEL/WebServices/", ResponseNamespace="https://www.valefiel.com/VALEFIEL/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InicioSesion IniciarSesionAfiliado(string UserName, string Password) {
            object[] results = this.Invoke("IniciarSesionAfiliado", new object[] {
                        UserName,
                        Password});
            return ((InicioSesion)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarSesionAfiliadoAsync(string UserName, string Password) {
            this.IniciarSesionAfiliadoAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAfiliadoAsync(string UserName, string Password, object userState) {
            if ((this.IniciarSesionAfiliadoOperationCompleted == null)) {
                this.IniciarSesionAfiliadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionAfiliadoOperationCompleted);
            }
            this.InvokeAsync("IniciarSesionAfiliado", new object[] {
                        UserName,
                        Password}, this.IniciarSesionAfiliadoOperationCompleted, userState);
        }
        
        private void OnIniciarSesionAfiliadoOperationCompleted(object arg) {
            if ((this.IniciarSesionAfiliadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionAfiliadoCompleted(this, new IniciarSesionAfiliadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.valefiel.com/VALEFIEL/WebServices/IniciarSesion", RequestNamespace="https://www.valefiel.com/VALEFIEL/WebServices/", ResponseNamespace="https://www.valefiel.com/VALEFIEL/WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InicioSesion IniciarSesion(string UserName, string Password, short IDRole) {
            object[] results = this.Invoke("IniciarSesion", new object[] {
                        UserName,
                        Password,
                        IDRole});
            return ((InicioSesion)(results[0]));
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string UserName, string Password, short IDRole) {
            this.IniciarSesionAsync(UserName, Password, IDRole, null);
        }
        
        /// <remarks/>
        public void IniciarSesionAsync(string UserName, string Password, short IDRole, object userState) {
            if ((this.IniciarSesionOperationCompleted == null)) {
                this.IniciarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIniciarSesionOperationCompleted);
            }
            this.InvokeAsync("IniciarSesion", new object[] {
                        UserName,
                        Password,
                        IDRole}, this.IniciarSesionOperationCompleted, userState);
        }
        
        private void OnIniciarSesionOperationCompleted(object arg) {
            if ((this.IniciarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IniciarSesionCompleted(this, new IniciarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.valefiel.com/VALEFIEL/WebServices/")]
    public partial class InicioSesion {
        
        private int iDPersonaAutenticadaField;
        
        private string sessionIDField;
        
        private int iDErrorField;
        
        private string mensajeErrorField;
        
        private RoleAcceso[] rolesPermiteAccesoField;
        
        /// <remarks/>
        public int IDPersonaAutenticada {
            get {
                return this.iDPersonaAutenticadaField;
            }
            set {
                this.iDPersonaAutenticadaField = value;
            }
        }
        
        /// <remarks/>
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public int IDError {
            get {
                return this.iDErrorField;
            }
            set {
                this.iDErrorField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public RoleAcceso[] RolesPermiteAcceso {
            get {
                return this.rolesPermiteAccesoField;
            }
            set {
                this.rolesPermiteAccesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.valefiel.com/VALEFIEL/WebServices/")]
    public partial class RoleAcceso {
        
        private short iDRoleField;
        
        private string nombreField;
        
        /// <remarks/>
        public short IDRole {
            get {
                return this.iDRoleField;
            }
            set {
                this.iDRoleField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void IniciarSesionAfiliadoCompletedEventHandler(object sender, IniciarSesionAfiliadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionAfiliadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionAfiliadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InicioSesion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InicioSesion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void IniciarSesionCompletedEventHandler(object sender, IniciarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IniciarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IniciarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InicioSesion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InicioSesion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591