//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_Content
    {
        public EC_Content()
        {
            this.EC_DetailContent = new HashSet<EC_DetailContent>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Tag { get; set; }
        public Nullable<int> IdParent { get; set; }
        public int IdUserAuthor { get; set; }
        public int IdTypeContent { get; set; }
        public System.DateTime Publishdate { get; set; }
        public string thumbail { get; set; }
    
        public virtual EC_TypeContent EC_TypeContent { get; set; }
        public virtual EC_Users EC_Users { get; set; }
        public virtual ICollection<EC_DetailContent> EC_DetailContent { get; set; }
    }
}
