//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_DetailContent
    {
        public int Id { get; set; }
        public string HtmlContent { get; set; }
        public int IdContent { get; set; }
    
        public virtual EC_Content EC_Content { get; set; }
    }
}
