//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_InfoUser
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Description { get; set; }
        public string Ocupacion { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual EC_Users EC_Users { get; set; }
    }
}
