//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EC_Users
    {
        public EC_Users()
        {
            this.EC_Content = new HashSet<EC_Content>();
            this.EC_News = new HashSet<EC_News>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public bool Enabled { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<EC_Content> EC_Content { get; set; }
        public virtual ICollection<EC_News> EC_News { get; set; }
        public virtual EC_InfoUser EC_InfoUser { get; set; }
    }
}
