//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECAEntities : DbContext
    {
        public ECAEntities()
            : base("name=ECAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EC_Content> EC_Content { get; set; }
        public DbSet<EC_DetailContent> EC_DetailContent { get; set; }
        public DbSet<EC_TypeContent> EC_TypeContent { get; set; }
        public DbSet<EC_Users> EC_Users { get; set; }
        public DbSet<EC_News> EC_News { get; set; }
    }
}
