//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ennovva.GCM.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivos
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public int IdAplication { get; set; }
        public string IdUsuario { get; set; }
    
        public virtual Aplicacion Aplicacion { get; set; }
    }
}
