//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ennovva.GCM.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GCMEntidades : DbContext
    {
        public GCMEntidades()
            : base("name=GCMEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplicacion> Aplicacion { get; set; }
        public virtual DbSet<Dispositivos> Dispositivos { get; set; }
        public virtual DbSet<Categoria_Lugar> Categoria_Lugar { get; set; }
        public virtual DbSet<Lugar> Lugar { get; set; }
        public virtual DbSet<LikesUsuario> LikesUsuario { get; set; }
        public virtual DbSet<ProveedorIdentidad> ProveedorIdentidad { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
